import { Geist, Fjalla_One, Geist_Mono, Exo, Teko } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  display: "swap",
});

// const vcr = localFont({
//   // src: "../public/fonts/VCR_OSD_Mono.ttf",
//   src: "../fonts/VCR_OSD_Mono.ttf",

//   variable: "--font-vcr", // 👈 this will create a CSS variable
//   weight: "400",
//   style: "normal",
// });

const fjallaOne = Fjalla_One({ 
  weight: '400',
  subsets: ['latin'],
});
const teko = Teko({
  subsets: ['latin'], // Or other desired subsets
  weight: ['300', '400', '500', '600', '700'], // Specify desired weights
  variable: '--font-teko', // Optional: for use with CSS variables
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // ${vcr.variable}
        className={`${geistSans.variable} ${fjallaOne.variable} ${geistMono.variable} ${exo.variable} ${teko.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
